name: Issue Tagged Workflow

on:
  issues:
    types: [opened, labeled]

jobs:
  check-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Check if issue has required tags
        id: check_tags
        uses: actions/github-script@v6
        with:
          script: |
            const requiredTags = ['gitops', 'stackspot'];
            const issueLabels = context.payload.issue.labels.map(label => label.name);
            const hasRequiredTags = requiredTags.every(tag => issueLabels.includes(tag));
            return hasRequiredTags;
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run workflow if tags are present
        if: steps.check_tags.outputs.result == 'true'
        run: echo "Issue has the required tags. Running workflow..."

      - name: Parse issue
        id: parse
        uses: onmax/issue-form-parser@v1.5
        with:
          issue_number: ${{ github.event.issue.number }}

      - name: Extract "outputs" from issue body
        id: extract_app_name
        uses: actions/github-script@v6
        with:
          script: |
            const issueBody = JSON.parse('${{ steps.parse.outputs.payload }}')
            for (const key in issueBody) {
              if (issueBody.hasOwnProperty(key)) {
                let key_slug = key.toLowerCase().trim().replace(/[^\w\s-]/g, '').replace(/[\s_-]+/g, '_').replace(/^-+|-+$/g, ''); 
                console.log(`${key_slug}: ${issueBody[key]}`);
                core.setOutput(key_slug, `${issueBody[key]}`);
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Repo App
        uses: repo-ctrl/create-repo-action@main 
        id: create-repo-app
        with:
          repo-name: 'app_${{ steps.extract_app_name.outputs.stk_project_name }}'
          org-admin-token: '${{ secrets.GHP_TOKEN }}'

      - name: Log URL to the repo
        run: echo "The new repo is ${{ steps.create-repo-app.outputs.repo-url }}"

      - name: Create Repo App Infra
        uses: repo-ctrl/create-repo-action@main 
        id: create-repo-app-infra
        with:
          repo-name: 'app_${{ steps.extract_app_name.outputs.stk_project_name }}'
          org-admin-token: '${{ secrets.GHP_TOKEN }}'

      - name: Log URL to the repo
        run: echo "The new repo is ${{ steps.create-repo-app-infra.outputs.repo-url }}"

      - name: Set timestamp
        run: |
          echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> "$GITHUB_ENV"

      - name: Stack Spot Workflow
        uses: stack-spot/workflow-github-action@main
        with:
          execution-id: "${{ steps.extract_app_name.outputs.execution-id }}"
          client-id: "${{ secrets.CLIENT_ID }}"
          client-secret: "${{ secrets.CLIENT_SECRET }}"
          realm: "${{ vars.REALM }}"
          debug: true
          repository-url: "${{ steps.create-repo-app-infra.outputs.repo-url }}"
          origin-branch: develop
          feature-branch: my-custom-feature-branch-${{ env.TIMESTAMP }}
          extra-inputs: '{"repository-url-infra": "${{ steps.create-repo-app-infra.outputs.repo-url }}"}'